[package]
name = "rust_os"
version = "0.1.0"
authors = ["Hannes Karppila <hannes.karppila@gmail.com>"]
publish = false

[lib]
crate-type = ["staticlib"]  # static and standalone

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
rlibc = "*"                     # raw libc
spin = "0.4"                    # spinlocks
cpuio = "0.2.0"                 # cpu port IO
bitflags = "0.7.0"              # bitflags
bit_field = "0.7.0"             # bit fields
volatile = "0.2.3"              # volatile read and write functions

[dependencies.x86]
default-features = false
version = "0.8.1"

[dependencies.d7alloc]
version = "*"
path = "libs/d7alloc"
