[package]
name = "rust_os"
version = "0.1.0"
authors = ["Hannes Karppila <hannes.karppila@gmail.com>"]
publish = false

[lib]
crate-type = ["staticlib"]  # static and standalone

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
# lto = true

[dependencies]
rlibc = "*"                     # raw libc
spin = "0.4.10"                 # spinlocks
cpuio = "0.2.0"                 # cpu port IO
bitflags = "1.0"                # bitflags
bit_field = "0.7.0"             # bit fields
volatile = "0.2.3"              # volatile read and write functions
static_assertions = "0.3.1"     # compile time assertions

[dependencies.x86_64]
default-features = false
version = "0.1.2"

[dependencies.d7alloc]
version = "*"
path = "libs/d7alloc"

[dependencies.d7staticfs]
version = "*"
path = "libs/d7staticfs"

[dependencies.d7ramfs]
version = "*"
path = "libs/d7ramfs"
