[package]
name = "d7os"
version = "0.1.0"
authors = ["Hannes Karppila <hannes.karppila@gmail.com>"]
publish = false
edition = "2018"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
rlibc = "*"
spin = "0.5"
cpuio = "0.2.0"
bitflags = "1.2"
bit_field = "0.10.0"
volatile = "0.2.6"
static_assertions = "1.1"
pinecone = "0.2"
log = "0.4"

[dependencies.hashbrown]
version = "0.7"
features = ["nightly", "inline-more", "serde"]

[dependencies.serde]
version = "1.0"
default-features = false
features = ["alloc", "derive"]

[dependencies.serde_json]
version = "1.0"
default-features = false
features = ["alloc"]

[dependencies.rand]
version = "0.7"
default-features = false
features = ["alloc", "small_rng"]

[dependencies.lazy_static]
version = "1.4"
features = ["spin_no_std"]

[dependencies.x86_64]
git = "https://github.com/Dentosal/x86_64"
features = ["use-serde"]

[dependencies.d7abi]
version = "*"
path = "libs/d7abi"

[dependencies.d7alloc]
version = "*"
path = "libs/d7alloc"

[dependencies.d7initrd]
version = "*"
path = "libs/d7initrd"

[dependencies.d7time]
version = "*"
path = "libs/d7time"
