[package]
name = "d7os"
version = "0.1.0"
authors = ["Hannes Karppila <hannes.karppila@gmail.com>"]
publish = false
edition = "2018"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
rlibc = "*"                     # raw libc
spin = "0.5"                    # spinlocks
cpuio = "0.2.0"                 # cpu port IO
bitflags = "1.2"                # bitflags
bit_field = "0.10.0"            # bit fields
volatile = "0.2.6"              # volatile read and write functions
static_assertions = "1.0"       # compile time assertions

[dependencies.hashbrown]        # HashMap for no_std contexts
version = "0.6.3"
features = ["nightly", "inline-more"]

[dependencies.lazy_static]      # Non-const_fn static intialization
version = "1.4"
features = ["spin_no_std"]

[dependencies.x86_64]           # x86-64 instructions and data structures
git = "https://github.com/Dentosal/x86_64"

[dependencies.d7abi]
version = "*"
path = "libs/d7abi"

[dependencies.d7alloc]
version = "*"
path = "libs/d7alloc"

[dependencies.d7staticfs]
version = "*"
path = "libs/d7staticfs"

[dependencies.d7ramfs]
version = "*"
path = "libs/d7ramfs"

[dependencies.d7time]
version = "*"
path = "libs/d7time"
