[package]
name = "rust_os"
version = "0.1.0"
authors = ["Hannes Karppila <hannes.karppila@gmail.com>"]

[lib]
crate-type = ["staticlib"]  # static and standalone

[dependencies]
rlibc = "1.0.0"             # raw libc
spin = "0.3.4"              # spinlocks
cpuio = "*"                 # cpu port IO
